### ISSUE TITLE
Illogical Readme

### ISSUE THREAD

**Issue by teknium1** [mehrdad-dev/Battle-of-the-Wordsmiths#1]
a) GPT-4 emerged as the top-performing chatbot across all categories, achieving a success rate of 84.1%. On the other hand, Bard faced challenges and achieved a success rate of 62.4%. b) Among the four models evaluated, one of them responded correctly approximately 93% of the time. However, all models were correct only about 44%. 

These statements don't make logical sense

**Comment by mehrdad-dev** [comment]
Hi dear @teknium1, 

Thanks for your attention to our paper.
We discussed these findings in the paper. Please look at the below sections of the paper:

For a) --> 4.3.1 Model accuracy and Figure 2
For b) --> 4.3.4 Model integration and Figure 5

Link to the preprint version of the paper:  https://www.researchgate.net/publication/371846888_Battle_of_the_Wordsmiths_Comparing_ChatGPT_GPT-4_Claude_and_Bard
